name: ADUXX-ZGLOSZENIA
version: '1.2'
main: dev.aduxx.aDUXXZGLOSZENIA.Main
api-version: '1.21'
description: System zgłoszeń
website: dc.lemonhost.pl
author: Aduxx

commands:
  zglos:
    aliases: [report]
